### PR TITLE
Don't remove me unless you do something with me!

### PR DESCRIPTION
**Pull request by thiakil**
Maybe will fix the thing

### CODE REVIEW

**Review by oitsjustjose — APPROVED** [review]

**Comment by oitsjustjose** [comment]
Prolly. Thanks for noticing. I've done so much with V-Tweaks that I can't remember.

**Comment by thiakil** [comment]
I thought further about this and it probably causes a dupe bug. whoops.

Instead maybe you should abort if the the player is `instanceof FakePlayer`

**Comment by oitsjustjose** [comment]
How do you theorize it’d create a dupe bug?

**Comment by thiakil** [comment]
i moved the iterator remove to only do it if it *cant* add to player inv, so if it *can* it will add it and it will still be spawned via normal methods

**Pull request merged**
